/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pilot_project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        // Create an instance of the class under test
        App classUnderTest = new App();
        // Check that the getGreeting method does not return null
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
