/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pilot_project;

public class App {
    // Method that returns a greeting message
    public String getGreeting() {
        return "Hello World!";
    }

    // Main method that serves as the entry point of the application
    public static void main(String[] args) {
        // Print the greeting message to the console
        System.out.println(new App().getGreeting());
    }
}
